[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "MICROSOFT_TENANT_ID"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 3000
