import { getValidAccessToken } from "../lib/google-auth.server";
import { prisma } from "../lib/prisma.server";
import pLimit from "p-limit";
import {
  currentDayWindow,
  isWithinWindow,
  toGmailDate,
  type DateWindow,
} from "../lib/date.server";
import {
  decodeHtmlEntities,
  stripHtml,
  stripQuotedReplies,
  MAX_BODY_CHARS,
} from "../lib/utils.server";
import type { EmailMessage, EmailProvider } from "./email-provider.server";

/** How many summaries the digest will hold in one run. */
const MAX_EMAILS = 5;
/**
 * How many messages to pull from the Gmail search before filtering. The
 * search lower bound is a whole day wide to absorb Gmail's Pacific-Time date
 * handling, so a busy inbox needs a wider net than the number of emails we
 * intend to keep.
 */
const SCAN_LIMIT = 15;

interface GmailMessagePart {
  partId: string;
  mimeType: string;
  filename: string;
  headers: { name: string; value: string }[];
  body: { size: number; data?: string; attachmentId?: string };
  parts?: GmailMessagePart[];
}

function decodeBase64Url(data: string): string {
  const base64 = data.replace(/-/g, "+").replace(/_/g, "/");
  return Buffer.from(base64, "base64").toString("utf-8");
}

/**
 * Picks the message body out of a MIME tree, preferring plain text.
 *
 * Returns text, never HTML. The HTML part is kept as a fallback and stripped
 * rather than ignored, because a great deal of real mail is HTML-only: a
 * multipart/alternative newsletter with no text/plain sibling, most marketing
 * mail, and anything generated by a design tool. Ignoring the HTML part meant
 * `getFullBody` returned an empty string for those, which left "view the
 * original" permanently blank and gave the summarizer subject-and-snippet only.
 *
 * A note on the choice not to pick the *richest* part: stripping HTML loses
 * link targets and table structure, so the plain-text part remains the
 * preference wherever both exist, and the HTML fallback is a last resort.
 */
function extractBody(payload: GmailMessagePart): string | null {
  const queue: GmailMessagePart[] = [payload];
  let htmlFallback: string | null = null;

  while (queue.length > 0) {
    const part = queue.shift()!;

    if (part.mimeType === "text/plain" && part.body?.data) {
      return decodeBase64Url(part.body.data);
    }
    if (htmlFallback === null && part.mimeType === "text/html" && part.body?.data) {
      htmlFallback = decodeBase64Url(part.body.data);
    }

    if (part.parts && part.parts.length > 0) {
      queue.push(...part.parts);
    }
  }

  if (htmlFallback === null) return null;

  const stripped = stripHtml(htmlFallback);
  return stripped.length > 0 ? stripped : null;
}

export class GmailProvider implements EmailProvider {
  async getTodaysEmails(userId: string): Promise<EmailMessage[]> {
    const accessToken = await this.getValidAccessToken(userId);
    return this.fetchMessages(accessToken, currentDayWindow());
  }

  async getValidAccessToken(userId: string): Promise<string> {
    return getValidAccessToken(userId);
  }

  async sendReply(
    userId: string,
    emailId: string,
    replyText: string,
  ): Promise<void> {
    const summary = await prisma.emailSummary.findUnique({
      where: { gmailMessageId: emailId },
    });
    if (!summary) {
      throw new Error("Email summary not found");
    }

    const accessToken = await this.getValidAccessToken(userId);

    // No In-Reply-To / References header: those must carry real Message-IDs,
    // and EmailSummary does not persist the original message's Message-ID or
    // threadId. Gmail falls back to subject-based threading, which is what
    // the previous (invalid, address-valued) header degraded to anyway.
    const rawMessage = [
      `To: ${summary.sender}`,
      `Subject: Re: ${summary.subject}`,
      `Content-Type: text/plain; charset=utf-8`,
      ``,
      replyText,
    ].join("\r\n");

    await this.postRaw(accessToken, rawMessage);

    // The `status = SENT` transition is the caller's job, not the provider's,
    // so that Microsoft Graph replies get marked too.
  }

  async sendNewMessage(
    userId: string,
    message: { to: string; subject: string; body: string },
  ): Promise<void> {
    const accessToken = await this.getValidAccessToken(userId);

    await this.postRaw(
      accessToken,
      [
        `To: ${message.to}`,
        `Subject: ${message.subject}`,
        `Content-Type: text/plain; charset=utf-8`,
        ``,
        message.body,
      ].join("\r\n"),
    );
  }

  /**
   * Base64url-encodes a raw RFC 822 message and hands it to `messages/send`.
   *
   * Shared by `sendReply` and `sendNewMessage` because the transport is
   * identical and only the headers differ — duplicating the encode-and-POST
   * dance would leave two places to fix a Gmail API change.
   */
  private async postRaw(accessToken: string, rawMessage: string): Promise<void> {
    const encodedMessage = Buffer.from(rawMessage)
      .toString("base64")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");

    const sendBody: { raw: string } = { raw: encodedMessage };

    const sendRes = await fetch(
      "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(sendBody),
      },
    );

    if (!sendRes.ok) {
      const errorText = await sendRes.text();
      throw new Error(`Gmail API error: ${sendRes.status} ${errorText}`);
    }
  }

  async getFullBody(userId: string, messageRef: string): Promise<string> {
    const accessToken = await this.getValidAccessToken(userId);
    const res = await fetch(
      `https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(messageRef)}?format=full`,
      { headers: { Authorization: `Bearer ${accessToken}` } },
    );

    if (!res.ok) return "";

    const data = (await res.json()) as { payload?: GmailMessagePart };
    if (!data.payload) return "";

    const body = extractBody(data.payload);
    if (!body) return "";

    const stripped = stripQuotedReplies(body);
    return stripped.length > MAX_BODY_CHARS
      ? stripped.slice(-MAX_BODY_CHARS)
      : stripped;
  }

  private async fetchMessages(
    accessToken: string,
    window: DateWindow,
  ): Promise<EmailMessage[]> {
    // Deliberately over-fetch by one day. Gmail resolves bare `after:` dates in
    // Pacific Time, so a local-midnight start either side of that boundary
    // would drop mail that genuinely arrived today; the exact filter is applied
    // below using Gmail's own receipt timestamp.
    const searchAfter = toGmailDate(new Date(window.start.getTime() - 24 * 60 * 60 * 1000));
    const params = new URLSearchParams({
      q: `after:${searchAfter}`,
      maxResults: String(SCAN_LIMIT),
    });

    const listRes = await fetch(
      `https://gmail.googleapis.com/gmail/v1/users/me/messages?${params.toString()}`,
      { headers: { Authorization: `Bearer ${accessToken}` } },
    );

    if (!listRes.ok) {
      const errorText = await listRes.text();
      throw new Error(`Gmail API error: ${listRes.status} ${errorText}`);
    }

    const listData = (await listRes.json()) as {
      messages?: { id: string }[];
    };

    if (!listData.messages) return [];

    // Concurrency is capped: this is one request per candidate message, and an
    // unbounded Promise.all over 15 of them is a good way to hit Gmail's
    // per-project rate limit.
    const limit = pLimit(5);

    const candidates = await Promise.all(
      listData.messages.map((msg) =>
        limit(async () => {
          const msgRes = await fetch(
            `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=metadata`,
            {
              headers: {
                Authorization: `Bearer ${accessToken}`,
                Accept: "application/json",
              },
            },
          );
          if (!msgRes.ok) return null;

          const msgData = (await msgRes.json()) as {
            id: string;
            threadId: string;
            snippet: string;
            // Milliseconds since epoch, as a string. This is Gmail's own
            // receipt time, so it is not spoofable by a sender's clock the way
            // the Date header is.
            internalDate?: string;
            payload?: {
              headers?: { name: string; value: string }[];
            };
          };

          const receivedAt = Number(msgData.internalDate);
          if (Number.isFinite(receivedAt) && !isWithinWindow(new Date(receivedAt), window)) {
            return null;
          }

          const headers = msgData.payload?.headers ?? [];
          const subject = decodeHtmlEntities(
            headers.find((h) => h.name === "Subject")?.value ?? "(no subject)",
          );
          const sender = decodeHtmlEntities(
            headers.find((h) => h.name === "From")?.value ?? "",
          );
          const date = headers.find((h) => h.name === "Date")?.value ?? "";
          const messageId =
            headers.find((h) => h.name === "Message-ID")?.value ?? "";
          return {
            id: msgData.id,
            threadId: msgData.threadId,
            messageId,
            subject,
            sender,
            snippet: decodeHtmlEntities(msgData.snippet ?? ""),
            date,
          } satisfies EmailMessage;
        }),
      ),
    );

    return candidates
      .filter((msg): msg is EmailMessage => msg !== null)
      .slice(0, MAX_EMAILS);
  }
}